t = 1 : 600;
x0 = [2, 0, 20, 0];
[y2, t, x] = initial(sys, x0, t);
figure(1);
subplot(2, 2, 1);
plot(t, y2(:, 1));
title('Raspunsul liber al sistemului');
xlabel("Timp[s]");
ylabel("Rata de tangaj[grd/s]");
subplot(2, 2, 2);
plot(t, y2(:, 2));
title('Raspunsul liber al sistemului');
xlabel("Timp[s]");
ylabel("Viteza pe axa OZ a SR atasat Pamantului[m/s]");
subplot(2, 2, 3);
plot(t, y2(:, 3));
title('Raspunsul liber al sistemului');
xlabel("Timp[s]");
ylabel("Viteza totala a aeronavei[m/s]");